services:
  hub:
    image: selenium/hub
    ports:
    - 4444:4444
  chrome :
    shm_size: '2g'
    image: selenium/node-chromium
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    deploy:
     replicas: 2
  firefox:
    shm_size: '2g'
    image: selenium/node-firefox
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  vendor-portal:
    image: sudha0425/automationselenium
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendorTest.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  fligh-reservation:
    image: sudha0425/automationselenium
    depends_on:
    - chrome
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output